# Generated by Django 4.2.4 on 2023-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='watchAgain',
            field=models.BooleanField(default=False),
        ),
    ]
